run:
  exclude-files:
    - lint/gorules.go
linters:
  enable:
    - exhaustruct
    - gocritic
linters-settings:
  exhaustruct:
    exclude:
      - '.*cobra\.Command$'
      - '.*http\.Cookie$'
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: "lint\\gorules.go"
