version: "2"
linters:
  enable:
    - exhaustruct
    - gocritic
  settings:
    exhaustruct:
      exclude:
        - .*cobra\.Command$
        - .*http\.Cookie$
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ifElseChain:
          minThreshold: 4
        ruleguard:
          rules: lint\gorules.go
    staticcheck:
      checks:
        all
        - -QF1001
        - -QF1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
