run:
  skip-files:
    - lint/gorules.go
linters:
  enable:
    - exhaustruct
    - gocritic
linters-settings:
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: "lint\\gorules.go"
