package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/goccy/go-json"
)

type tzRow struct {
	Name               string
	AlternativeName    string
	Group              []string
	RawOffsetInMinutes int
	RawFormat          string
}

type friendlyTimezone struct {
	groupId                 string
	friendlyName            string
	shortFriendlyPrefixName string
	shortFriendlySuffixName string
}

func main() {
	// From https://github.com/vvo/tzdb/blob/main/raw-time-zones.json
	jsonFile, err := os.Open("cmd/timezones/raw-time-zones.json")
	if err != nil {
		panic(err)
	}
	defer jsonFile.Close()

	decoder := json.NewDecoder(jsonFile)
	var tzRows []tzRow
	if err := decoder.Decode(&tzRows); err != nil {
		panic(err)
	}

	overrides := map[string]friendlyTimezone{
		"Pacific/Kanton": {
			groupId:                 "Pacific/Enderbury",
			friendlyName:            "+13:00 Phoenix Islands Time - Endenbury",
			shortFriendlyPrefixName: "+13:00 Phoenix Islands Time",
			shortFriendlySuffixName: "Phoenix Islands Time (+13:00)",
		},
	}

	var friendlyTimezones []friendlyTimezone
	tzdbGroups := make(map[string]bool)
	for _, tzRow := range tzRows {
		var friendlyTz friendlyTimezone
		if override, ok := overrides[tzRow.Name]; ok {
			friendlyTz = override
		} else {
			sign := "+"
			offsetAbs := tzRow.RawOffsetInMinutes
			if tzRow.RawOffsetInMinutes < 0 {
				sign = "-"
				offsetAbs = -tzRow.RawOffsetInMinutes
			}
			hours := offsetAbs / 60
			minutes := offsetAbs % 60
			shortFriendlyPrefixName :=
				fmt.Sprintf("%s%02d:%02d %s", sign, hours, minutes, tzRow.AlternativeName)
			shortFriendlySuffixName :=
				fmt.Sprintf("%s (%s%02d:%02d)", tzRow.AlternativeName, sign, hours, minutes)
			friendlyTz = friendlyTimezone{
				groupId:                 tzRow.Name,
				friendlyName:            tzRow.RawFormat,
				shortFriendlyPrefixName: shortFriendlyPrefixName,
				shortFriendlySuffixName: shortFriendlySuffixName,
			}
		}

		friendlyTimezones = append(friendlyTimezones, friendlyTz)
		tzdbGroups[friendlyTz.groupId] = true
	}

	groupIdByTz := make(map[string]string)
	tzdbTimezones := make(map[string]bool)
	for _, tzRow := range tzRows {
		for _, timezone := range tzRow.Group {
			if tzdbTimezones[timezone] {
				continue
			}
			tzdbTimezones[timezone] = true
			var groupId string
			if override, ok := overrides[tzRow.Name]; ok {
				groupId = override.groupId
			} else {
				groupId = tzRow.Name
			}
			groupIdByTz[timezone] = groupId
		}
	}

	shortFriendlyPrefixNameByGroupId := make(map[string]string)
	shortFriendlySuffixNameByGroupId := make(map[string]string)
	for _, friendlyTz := range friendlyTimezones {
		shortFriendlyPrefixNameByGroupId[friendlyTz.groupId] = friendlyTz.shortFriendlyPrefixName
		shortFriendlySuffixNameByGroupId[friendlyTz.groupId] = friendlyTz.shortFriendlySuffixName
	}
	shortFriendlyPrefixNameByGroupIdJson, err := json.Marshal(&shortFriendlyPrefixNameByGroupId)
	if err != nil {
		panic(err)
	}
	shortFriendlySuffixNameByGroupIdJson, err := json.Marshal(&shortFriendlySuffixNameByGroupId)
	if err != nil {
		panic(err)
	}
	groupIdByTimezoneIdJson, err := json.Marshal(&groupIdByTz)
	if err != nil {
		panic(err)
	}

	const minOffset = -14
	const maxOffset = 12
	type UnfriendlyOffsetGroupId struct {
		offset  int
		groupId string
	}
	var unfriendlyOffsetGroupIds []UnfriendlyOffsetGroupId
	for offset := minOffset; offset <= maxOffset; offset++ {
		offsetStr := fmt.Sprint(offset)
		if offset >= 0 {
			offsetStr = "+" + offsetStr
		}
		unfriendlyOffsetGroupIds = append(unfriendlyOffsetGroupIds, UnfriendlyOffsetGroupId{
			offset:  offset,
			groupId: fmt.Sprintf("Etc/GMT%s", offsetStr),
		})
	}

	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by cmd/timezones; DO NOT EDIT")
	fmt.Fprintln(&b, "package util")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import "html/template"`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type FriendlyTimezone struct {")
	fmt.Fprintln(&b, "    GroupId string")
	fmt.Fprintln(&b, "    FriendlyName string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "var FriendlyTimezones = []FriendlyTimezone {")
	for _, friendlyTz := range friendlyTimezones {
		fmt.Fprintf(&b, "    {%q, %q},\n", friendlyTz.groupId, friendlyTz.friendlyName)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "var GroupIdByTimezoneId = map[string]string {")
	for tz, groupId := range groupIdByTz {
		fmt.Fprintf(&b, "    %q: %q,\n", tz, groupId)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "const ShortFriendlyPrefixNameByGroupIdJson = template.JS(%q)\n", shortFriendlyPrefixNameByGroupIdJson)
	fmt.Fprintf(&b, "const ShortFriendlySuffixNameByGroupIdJson = template.JS(%q)\n", shortFriendlySuffixNameByGroupIdJson)
	fmt.Fprintf(&b, "const GroupIdByTimezoneIdJson = template.JS(%q)\n", groupIdByTimezoneIdJson)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `const TimezoneUTC = "UTC"`)
	fmt.Fprintln(&b, `var UnfriendlyGroupIdByOffset = map[int]string{`)
	for _, offsetGroupId := range unfriendlyOffsetGroupIds {
		fmt.Fprintf(&b, `    %d: %q,`, offsetGroupId.offset, offsetGroupId.groupId)
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, `}`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `var UnfriendlyGroupIds = map[string]bool{`)
	for _, offsetGroupId := range unfriendlyOffsetGroupIds {
		fmt.Fprintf(&b, `    %q: true,`, offsetGroupId.groupId)
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, `    TimezoneUTC: true,`)
	fmt.Fprintln(&b, `}`)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(err)
	}

	err = os.WriteFile("util/timezones.go", formatted, 0666)
	if err != nil {
		panic(err)
	}
}
